### ISSUE TITLE
Dart_IntegerToInt64 expects argument 'integer' to be non-null.

### ISSUE THREAD

**Issue by austincummings** [aam/oracledart#21]
Hello again @aam,

My server is crashing with this error `Dart_IntegerToInt64 expects argument 'integer' to be non-null.` when I try to call
`resultSet.getStringByName("column")`. I have dug into your code and believe it may be coming from `OracleMetadataVector_GetColumnName` or `OracleResultSet_Get`. 

Do you have any ways to work around this?

**Comment by aam** [comment]
I think the reason for this error is that oracledart can't find column with "column" name. I think column names should be all uppercases - that's what Oracle expects as far as I know.
You can confirm list of columns by scanning result of resultset.getMetadataVector().

```dart
OracleMetadataVector metadata = resultset.getMetadataVector();
    var columns = {};
    for (int i = 0; i < metadata.getSize(); i++) {
      columns[metadata.getColumnName(i)] = i + 1;
    }
    resultset.next();
```

**Comment by austincummings** [comment]
Yeah I was accessing a non-existant column. Is there anyway there could be a better error message? Or perhaps an exception thrown. I'll happily contribute the code when I get the chance.

**Comment by aam** [comment]
Absolutely there could and there should.
