### ISSUE TITLE
Question: Use of import "dart:nativewrappers"?

### ISSUE THREAD

**Issue by austincummings** [aam/oracledart#26]
Is `import "dart:nativewrappers"` needed in `lib/src/oracledart_native.dart`? I don't see anything that uses it and it breaks dartdocgen.

**Comment by aam** [comment]
Yeah, it is needed for native extension class wrappers.

It's really unfortunate about dartdocgen. One thing you can do if you want to generate documentation - just get rid of oracledart_native.dart and references to it when you run dartdocgen.

Alexander Aprelev.

________________________________
