### ISSUE TITLE
Extracting a CLOB from result set

### ISSUE THREAD

**Issue by austincummings** [aam/oracledart#28]
Hey @aam,

I was wondering if it's possible to pull a CLOB out of a result set like the title says. I try to `getString` on it but it seems to return an empty string.

Thanks!

**Comment by aam** [comment]
API for accessing CLOBs is different from the one used to access Strings.
So CLOB data type support needs to be added before you can retrieve them.

**Comment by aam** [comment]
I mean the main complexity with mapping this to Dart is passing untyped bytestream from/to c++ to Dart. Or more like providing mechanisms in your Dart app to handle(parse, create) it.

**Comment by austincummings** [comment]
Thanks for the info. Would it be possible to put the result into a [ByteBuffer](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:typed_data.ByteBuffer)? I believe Dart has special functions in dart_api.h to allow for creating these.

**Comment by aam** [comment]
Yes, thanks for the tip, @austincummings .
Do you want to take a look at 0.0.13? I added getClob() method to OracleResultset in that version.

**Comment by austincummings** [comment]
This is great man. I'm getting an error when I try to call the new function. Seems that it's returning _ByteBuffer rather than ByteBuffer. Any ideas?

```
'package:oracledart/src/oracledart_native.dart': malformed type: line 57 pos 3: cannot resolve class 'ByteBuffer' from '_OracleResultset@1040786739'
  ByteBuffer getClob(int index) native "OracleResultset_GetClob";
  ^
type '_ByteBuffer' is not a subtype of type 'malformed' of 'function result'.

package:oracledart/src/oracledart_native.dart 57:65  _OracleResultset.getClob
package:webquery/server/database_helper.dart 118:75  DatabaseHelper.query
package:webquery/server/otes.dart 86:32              OtesSciRawDataProductsResource.search
dart:mirrors                                         _LocalInstanceMirror.invoke
package:redstone/src/setup_impl.dart 728:34          _configureTarget..
package:redstone/src/setup_impl.dart 792:28          _configureTarget..
```

**Comment by aam** [comment]
Yeah, forgot import statement. Didn't catch it because I was running tests in production mode where there are no type checks. Added import statements and switched tests into checked mode.
Version 0.0.14 should have the fix.

**Comment by austincummings** [comment]
Works great. Thanks for all the help and speedy responses.
